from __future__ import division
import argparse
import configparser
import os
import sys

parser = argparse.ArgumentParser()
parser.add_argument("-d", type=str, action='store', dest='dir', metavar='INPUT',help='define dir')
parser.add_argument("-d2", type=str, action='store', dest='dir2', metavar='INPUT',help='define orig dir')
parser.add_argument("-t", type=str, action='store', dest='tolid', metavar='INPUT',help='define tolid')
parser.add_argument("-l", type=str, action='store', dest='binlist', metavar='INPUT',help='define binlist')
parser.add_argument("-g", type=str, action='store', dest='gfa', metavar='GFA',help='define gfa file')
parser.add_argument('--version', action='version', version='%(prog)s 1.0')
results = parser.parse_args()

binlistfile=open(results.binlist,'w')

m =open(results.dir,'r')
totalfound=0
total_busco=0
complete=0
dirshort=results.dir.split('/buscoAssembly/completeness_per_contig.txt')[0]
for rec in m:
    if not rec.startswith('#'):
        ctg=rec.split('\t')[0]
        totalfound+=int(rec.split('\t')[1])
        total_busco=int(rec.split('\t')[2])
        if float(rec.split('\t')[3].split('%')[0]) > 97 and float(rec.split('\t')[5]) > 700000 and float(rec.split('\t')[5]) < 2400000:
            complete+=1
m.close()

totalfound2=0
total_busco2=0
complete2=0
k=open(dirshort+'/busco/completeness_per_contig.txt')
for rec in k:
    if not rec.startswith('#'):
        ctg=rec.split('\t')[0]
        totalfound2+=int(rec.split('\t')[1])
        total_busco2=int(rec.split('\t')[2])
        if float(rec.split('\t')[3].split('%')[0]) > 97 and float(rec.split('\t')[5]) > 700000 and float(rec.split('\t')[5]) < 2400000:
            complete2+=1
k.close()
print(str(totalfound2)+','+str(total_busco2)+','+str(complete2))

contignumber=1
m =open(results.dir,'r')
if totalfound/total_busco >0.97 and round(totalfound/total_busco)==complete:
    for record in m:
        record=record.strip()
        if not record.startswith('#'):
            if float(record.split('\t')[3].split('%')[0]) > 97 and float(record.split('\t')[5]) > 700000 and float(record.split('\t')[5]) < 2400000:
                print(record)
                ctg=record.split('\t')[0]
                if ctg.endswith('c'):
                    print(ctg)
                    gfafile=dirshort+'/hifiasm/hifiasm.p_ctg.gfa'
                    n=open(gfafile,'r')
                    coverage=0
                    for line in n:
                        line=line.strip()
                        if line.startswith('S\t'+ctg):
                            coverage=int(line.split('\t')[4].split(':')[2])
                    n.close()
                    print(coverage)
                    meta=open(dirshort+'/'+results.tolid+'.Wolbachia_sp_'+str(contignumber)+'.1.metadata.txt', 'w')
                    meta.write('The assembly '+results.tolid+'.Wolbachia_sp_'+str(contignumber)+'.1 is based on '+str(coverage)+"x PacBio data generated by the Darwin Tree of Life Project (https://www.darwintreeoflife.org/). The PacBio assembly was generated with Hifiasm.\n")
                    meta.close()
                    lst=open(dirshort+'/'+results.tolid+'.Wolbachia_sp_'+str(contignumber)+'.1.list', 'w')
                    lst.write(ctg+'\t1\tCircular-Chromosome\n')
                    lst.close()
                    fafile=open(dirshort+'/'+results.tolid+'.Wolbachia_sp_'+str(contignumber)+'.1.fa', 'w')
                    fasta=dirshort+'/hifiasm/hifiasm.p_ctg.fasta'
                    n=open(fasta,'r')
                    inline=False
                    for line in n:
                        if line.startswith('>'):
                            if ctg in line:
                                inline=True
                                fafile.write(line)
                            else:
                                inline=False
                        else:
                            if inline == True:
                                fafile.write(line)
                    n.close()
                    fafile.close()
                    binlistfile.write(results.tolid+'.Wolbachia_sp_'+str(contignumber)+'.1\n')
                    contignumber+=1
                else:
                    print(ctg)
                    ctgs=[]
                    ctgs.append(ctg)
                    #buscotable=dirshort+'/buscoAssembly/busco/run_rickettsiales_odb10/full_table.tsv'
                    buscotable=dirshort+'/buscoAssembly/full_table.tsv'
                    buscofound=[]
                    buscofound_additional={}

                    b=open(buscotable)
                    for line in b:
                        line=line.strip()
                        if ctg in line:
                            buscofound.append(line.split('\t')[0])
                        elif not line.startswith('#') and not 'Missing' in line:
                            print(line)
                            if not line.split('\t')[2] in buscofound_additional:
                                buscofound_additional[line.split('\t')[2]]=[]
                            buscofound_additional[line.split('\t')[2]].append(line.split('\t')[0]) 
                    b.close()

                    b=open(buscotable)
                    for novelctg in buscofound_additional:
                        totalbusco=0
                        for line in b:
                            line=line.strip()
                            if novelctg in line:
                                if not line.split('\t')[0] in buscofound:
                                    print(line)
                                    totalbusco+=1
                        print(novelctg+'\t'+str(totalbusco)+'\t'+str(len(buscofound_additional[novelctg]))+'\t'+','.join(buscofound_additional[novelctg]))
                        if totalbusco == len(buscofound_additional[novelctg]):
                            print(','.join(buscofound_additional[novelctg]))
                            ctgs.append(novelctg)
                    b.close()

                    gfafile=dirshort+'/hifiasm/hifiasm.p_ctg.gfa'
                    n=open(gfafile,'r')
                    final_coverage=0
                    if len(ctgs) == 1:
                        for line in n:
                            line=line.strip()
                            if line.startswith('S\t'+ctg):
                                final_coverage=int(line.split('\t')[4].split(':')[2])
                        print(final_coverage)
                        lst=open(dirshort+'/'+results.tolid+'.Wolbachia_sp_'+str(contignumber)+'.1.list', 'w')
                        lst.write(ctg+'\t1\tLinear-Chromosome\n')
                        lst.close()
                    else:
                        calc_cov=0
                        total_len=0
                        for line in n:
                            line=line.strip()
                            if line.startswith('S') and line.split('\t')[1] in ctgs:
                                cov=int(line.split('\t')[4].split(':')[2])
                                if cov == 0:
                                    cov=1
                                length=int(line.split('\t')[3].split(':')[2])
                                total_len+=length
                                calc_cov+=(cov*length)
                                print(line.split('\t')[1]+'\t'+str(length)+'\t'+str(cov))    
                        final_coverage=int(calc_cov/total_len)
                    n.close()
                    meta=open(dirshort+'/'+results.tolid+'.Wolbachia_sp_'+str(contignumber)+'.1.metadata.txt', 'w')
                    meta.write('The assembly '+results.tolid+'.Wolbachia_sp_'+str(contignumber)+'.1 is based on '+str(final_coverage)+"x PacBio data generated by the Darwin Tree of Life Project (https://www.darwintreeoflife.org/). The PacBio assembly was generated with Hifiasm.\n")
                    meta.close()
                    fafile=open(dirshort+'/'+results.tolid+'.Wolbachia_sp_'+str(contignumber)+'.1.fa', 'w')
                    fasta=dirshort+'/hifiasm/hifiasm.p_ctg.fasta'
                    n=open(fasta,'r')
                    inline=False
                    for line in n:
                        if line.startswith('>'):
                            if line.split()[0].split('>')[1] in ctgs:
                                print(line)
                                inline=True
                                fafile.write(line)
                            else:
                                inline=False
                        else:
                            if inline == True:
                                fafile.write(line)
                    n.close()
                    fafile.close()
                    binlistfile.write(results.tolid+'.Wolbachia_sp_'+str(contignumber)+'.1\n')
                    contignumber+=1
#elif total_busco2 > 0 and totalfound2/total_busco2 >0.97:               
else:
    binlistfile.write(results.tolid+'.Wolbachia_sp_'+str(contignumber)+'.1\n')
    fafile=dirshort+'/'+results.tolid+'.Wolbachia_sp_'+str(contignumber)+'.1.fa'
    orig_fafile=results.dir2+'/Anaplasmataceae.finalassembly.fa'
    cmd="cp "+orig_fafile+" "+fafile
    os.system(cmd)
    
    ctglist=[]
    n=open(orig_fafile,'r')
    for line in n:
        line=line.strip()
        if line.startswith('>'):
            ctglist.append(line.split('>')[1])
    n.close()

    calc_cov=0
    total_len=0
    gfafile2=results.gfa.split('.p_ctg')[0]+'.a_ctg.noseq.gfa'
    gfafiles=[results.gfa, gfafile2]
    for gfa in gfafiles:
        l=open(gfa,'r')
        for line in l:
            line=line.strip()
            if line.startswith('S') and line.split('\t')[1] in ctglist:
                cov=int(line.split('\t')[4].split(':')[2])
                if cov == 0:
                    cov=1
                length=int(line.split('\t')[3].split(':')[2])
                total_len+=length
                calc_cov+=(cov*length)
                print(line.split('\t')[1]+'\t'+str(length)+'\t'+str(cov))
        l.close()
    final_coverage=0
    if total_len > 0:
        final_coverage=int(calc_cov/total_len)
        manifestfile=open(dirshort+'/'+results.tolid+'.Wolbachia_sp_'+str(contignumber)+'.1.manifest.txt','w')
        manifestfile.write('STUDY\t\nSAMPLE\t\nASSEMBLYNAME\t'+results.tolid+'.Wolbachia_sp_'+str(contignumber)+'.1\nASSEMBLY_TYPE\tMetagenome-Assembled Genome (MAG)\nCOVERAGE\t'+str(final_coverage)+'X\nPROGRAM\tHifiasm\nPLATFORM\tPacBio Sequel II (HiFi)\nMOLECULETYPE\tgenomic DNA\nFASTA\t'+results.tolid+'.Wolbachia_sp_'+str(contignumber)+'.1.mag.fa\n')
        manifestfile.close()

    contignumber+=1
binlistfile.close()
m.close()